### ISSUE TITLE
Shadow of Mordor not working

### ISSUE THREAD

**Issue by Lecreuset** [KrossX/Durazno#9] opened 2016-02-10 17:58 UTC
Thank you so much for this!
Like the other user, I also signed up just to say how awesome it was to be able to play Shadow of Mordor, and not feel like I wasted my money on a game that wouldn't invert both axes.
However, at the beginning of this month, it seems to have stopped working out of the blue.
I'm unsure if it was a game update, or something with Steam.
Truthfully I was hoping I was doing something stupid which made it stop working, but that doesn't seem to be the case.
I realize you don't know me, or owe me anything...
I was hoping if you had the free time if you could give me a hand of some sort with it.
If there's any specific information that might help beyond the fact I use the Rock Candy XBox 360 Wired USB Controller, I'd be glad to make mention.
I tried to use X360Ce to avoid bothering you with this, and while it fixed the inversion, the triggers were boned.
At any rate, even if nothing can be done, thanks for helping me get some time into the game!

**Comment by KrossX** [comment] 2016-02-11 02:35
Alright, I'll use this instead of the steam forum as I get email notifications.

You mentioned the tool worked with the default filename. That's alright, as the tool only works with that name. Then x360ce works, so that means the wrappers in general seem to still work.

Just making sure of having the ini file made, and then the dll renamed to the one used with x360ce should've done the trick already. Are you using the 64bit or 32bit version of x360ce?

**Comment by Lecreuset** [comment] 2016-02-11 14:31
Yes I tried the 64bit version of x360ce after I noticed the controls weren't inverted anymore when I tried to play. Though it fixed the inversion problem, the triggers suddenly wouldn't work properly. (In Shadow of Mordor, the left trigger brings you to bow/arrow firing mode, and while depressed you can charge/fire shots with the right trigger.)

In the beginning with Durazno I had the exe, dll (renamed), and ini file in the game exe folder. It just seemed to have oddly changed back when I tried to play at the beginning of this month.

**Comment by KrossX** [comment] 2016-02-11 17:00
Can you make sure to be using the 64bit version of Durazno as well? Make sure the settings work on the test tab before renaming the dll.

**Comment by Lecreuset** [comment] 2016-02-11 17:14
Absolutely.
I went into the Durazno\x64 folder, and copied those files to my ShadowOfMordor\x64 folder.
The settings worked on the test tab. I renamed the dll, loaded the game, and nada.

**Comment by KrossX** [comment] 2016-02-11 17:24
Can you zip me that "ShadowOfMordor\x64" folder? I'll need to analyze that. Upload it somewhere and post the link please.

**Comment by Lecreuset** [comment] 2016-02-11 17:45
Absolutely can. I wanted to try it with Skyrim also. The ini/dll just go in the folder where the game's executable is? Also, aside photos, I've never really had to upload much. Hopefully this'll work. [Link.](https://www.dropbox.com/sh/ptz38c0ywqleucb/AAC9zzsWsb5lyCVcwGvsELi8a?dl=0)

**Comment by KrossX** [comment] 2016-02-11 18:05
That worked, thanks. I'll let you know if I find something from it.

And yes, all you need is the dll and the ini for the settings. The tricky part can be finding out what dll name the game requires.

PS: You can delete that from your Dropbox now.

**Comment by Lecreuset** [comment] 2016-02-11 18:48
Apologies as I forgot to zip it. Thank you!

**Comment by KrossX** [comment] 2016-02-11 19:10
No problem, you can dowload it as a zip package from Dropbox. 

I haven't found anything odd with the game as it does appear to load the durazno dll without issue. To see what happens ingame, I made this dll that has some logging. [Durazno Test](https://drive.google.com/open?id=0B1wssOeJs5_7VVJZV3BNenBkLWs)

Keep your settings, run the game, use the controlller and exit. See if the **duranzo.log** file is there and attach it here. Also, when you say that nothing happens when using Durazno, the gamepad still works right? Just not the customization?

**Comment by Lecreuset** [comment] 2016-02-11 19:21
[This is the link to the log file on Dropbox.](https://www.dropbox.com/sh/ptz38c0ywqleucb/AAC9zzsWsb5lyCVcwGvsELi8a?dl=0)

This is the text in the log file.

== DURAZNO LOG BEGIN ==
XInputGetState : (0) durazno_init
LoadCustomDLL
SUCCESS
durazno_shutdown
== DURAZNO LOG CLOSE ==

**Comment by Lecreuset** [comment] 2016-02-11 19:22
The gamepad (Rock Candy XBox 360 Wired USB Controller) still works, just no inversion/customizations from Durazno.

**Comment by KrossX** [comment] 2016-02-11 19:58
It's like it's used once then never again. The game doesn't like my wrapper, then just ditches it. =(

New file, same test. [Durazno Test 2](https://drive.google.com/open?id=0B1wssOeJs5_7RExORTR6MVNfQkU)

**Comment by Lecreuset** [comment] 2016-02-12 00:45
[Log File Link](https://www.dropbox.com/sh/ptz38c0ywqleucb/AAC9zzsWsb5lyCVcwGvsELi8a?dl=0)

Log Text:
== DURAZNO LOG BEGIN ==
durazno_init
LoadCustomDLL : 
durazno_init : SUCCESS, C:\WINDOWS\system32\XINPUT9_1_0.dll
XInputGetState : (0) SUCCESS
durazno_shutdown
== DURAZNO LOG CLOSE ==

**Comment by KrossX** [comment] 2016-02-12 03:03
Dang it. I have no idea why it suddenly stops working. I might be able to make code some testing application based on the game files you sent me, worth a try.

So far, consider the game unsupported. =S

**Comment by Lecreuset** [comment] 2016-02-12 14:28
Okay. It was working wonderfully until February. I've played about 12 hours of the game with it working through January. I know Steam had a few updates, but I doubt they're related to that.

**Comment by Lecreuset** [comment] 2016-02-20 20:01
I'll be out of town a few days to a week or so. If this is something you might pursue further, if there's anything I can do to help, please lmk. ^_^

**Comment by KrossX** [comment] 2016-02-21 14:06
Surething. I'll let you know if I have something to test.

**Comment by KrossX** [comment] 2016-03-02 23:26
I haven't been able to make a test case. I updated Durazno a bit before, I doubt it would make a difference but give it a try please.

Other than that, I have a few things that might give enough information. Reaching a gameplay point then exit, one would be using 360ce since it worked for you but with logging enabled; another one, would be using ApiMonitor with everything enabled while using Durazno and posting the capture here. Let me know if you're interested.

**Comment by Lecreuset** [comment] 2016-03-03 23:22
I'll download it and give it a go!

As far as the other ideas go, glad to give them a try.

**Comment by Lecreuset** [comment] 2016-03-03 23:31
With the new one I've downloaded, it doesn't show the inversion in the test area even after clicking the invert X and Y on the right stick.

**Comment by KrossX** [comment] 2016-03-04 00:00
I think it's fixed now. It was an issue in the GUI, so the wrapper should've worked (or not worked) the same.

Alright, so for the extra logs you already have x360ce so just enable logging or put Log=1 in the INI. Get to a gameplay point and exit, post the log in here.

As for ApiMonitor, you can get it from here: [API Monitor](http://www.rohitab.com/downloads) and just get the v2 portable one. Make sure to be **offline** while doing this, as I dunno if it could be detected as a cheat. Use the x64 version, enable all the things to trace and use "Monitor new process" to run the game. While using Durazno reach the same point as the previous test, save the capture (File -> save) and post it here (big file warning).

**Comment by KrossX** [comment] 2016-03-17 16:22
Can you give this build a try please? [durazno_test3](https://drive.google.com/open?id=0B1wssOeJs5_7ekgxb18yTXY4YjQ)

Beware of error messages.

**Comment by Lynnifer** [comment] 2016-05-26 15:27
Here's my Shadow of [Morder/x64 folder](https://www.dropbox.com/s/f99o8h8sj5wqukz/Shadow%20of%20Mordor%20x64.zip?dl=0).

When I rename the dll to xinput9_1_0.dll and reopen the application to look at the test tab, the upper area shows no movement of the stick at all, and the bottom area shows uninverted movement.

**Comment by KrossX** [comment] 2016-05-28 18:05
Thanks, and that's normal. 

The application only loads the default dll. The idea was to just use the program to make the ini then copy the ini/dll and do the necessary renaming.

**Comment by KrossX** [comment] 2016-05-28 18:58
@Lynnifer I could not reproduce it. Can you please test extracting [this files](https://drive.google.com/open?id=0B1wssOeJs5_7Q19MeXg2ZDRrSmM) into your Mordor\x64 folder? Left stick should behave inverted.

**Comment by Lynnifer** [comment] 2016-05-28 19:13
Neither of the sticks were inverted.

**Comment by KrossX** [comment] 2016-05-29 02:19
I am clueless about this. I had hoped a game update changed the behavior to make Durazno no longer work with it, but nothing odd happened on my test.

There should be a Durazno.log file being created, delete it. Then please replace the files again with those given in the previous post and test again. Please post here the contents of the new log file.

**Comment by Lynnifer** [comment] 2016-05-29 17:05
= Durazno Log Opened =
DllMain: DLL_PROCESS_ATTACH
XInputLoadLibrary: C:\WINDOWS\system32\XINPUT9_1_0.dll
XInputGetProc: XInputGetState

**Comment by KrossX** [comment] 2016-05-30 16:25
Thank you very much. I'll try to make some better log messages on the weekend.

**Comment by Lynnifer** [comment] 2016-05-31 15:17
Thanks so much for trying to fix this.  I'd love to play the game someday.  :)

**Comment by KrossX** [comment] 2016-06-01 06:57
How about giving [Xinput Plus](https://sites.google.com/site/0dd14lab/xinput-plus) a try? I never tried it, but might just work. Let me know if it works please,

**Comment by Lynnifer** [comment] 2016-06-01 17:12
It worked!  Thank you so much for suggesting it.

**Closed** 2017-04-12 21:46 UTC
